# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\DYU\Desktop\0118demo\dcon_protocol_ui-develop\zhi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from analoggaugewidget import AnalogGaugeWidget

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1459, 830)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setMouseTracking(False)
        Form.setTabletTracking(False)
        Form.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(Form)
        Form.setWindowFlags(QtCore.Qt.WindowMinimizeButtonHint | QtCore.Qt.WindowCloseButtonHint | QtCore.Qt.WindowStaysOnTopHint)
        Form.setStyleSheet("background-color:rgb(233, 236, 255)")
        self.widget_0 = QtWidgets.QWidget(Form)
        self.widget_0.setGeometry(QtCore.QRect(1250, 100, 121, 71))
        self.widget_0.setStyleSheet("border-radius: 10px;\n"
"image: url(:/unchecked-radio-button-off-96.png);")
        self.widget_0.setObjectName("widget_0")
        self.widget_1 = QtWidgets.QWidget(Form)
        self.widget_1.setGeometry(QtCore.QRect(1100, 100, 121, 71))
        self.widget_1.setStyleSheet("border-radius: 10px;\n"
"image: url(:/unchecked-radio-button-off-96.png);")
        self.widget_1.setObjectName("widget_1")
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setGeometry(QtCore.QRect(950, 100, 121, 71))
        self.widget_2.setStyleSheet("border-radius: 10px;\n"
"image: url(:/unchecked-radio-button-off-96.png);")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(Form)
        self.widget_3.setGeometry(QtCore.QRect(160, 330, 121, 71))
        self.widget_3.setStyleSheet("border-radius: 10px;\n"
"image: url(:/unchecked-radio-button-off-96.png);")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(Form)
        self.widget_4.setGeometry(QtCore.QRect(10, 330, 111, 71))
        self.widget_4.setStyleSheet("border-radius: 10px;\n"
"image: url(:/unchecked-radio-button-off-96.png);")
        self.widget_4.setObjectName("widget_4")
        self.widget_5 = QtWidgets.QWidget(Form)
        self.widget_5.setGeometry(QtCore.QRect(0, 510, 131, 61))
        self.widget_5.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_5.setObjectName("widget_5")
        self.widget_7 = QtWidgets.QWidget(Form)
        self.widget_7.setGeometry(QtCore.QRect(0, 620, 131, 61))
        self.widget_7.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_7.setObjectName("widget_7")
        self.widget_8 = QtWidgets.QWidget(Form)
        self.widget_8.setGeometry(QtCore.QRect(0, 680, 131, 61))
        self.widget_8.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_8.setObjectName("widget_8")
        self.widget_9 = QtWidgets.QWidget(Form)
        self.widget_9.setGeometry(QtCore.QRect(150, 620, 131, 61))
        self.widget_9.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_9.setObjectName("widget_9")
        self.widget_10 = QtWidgets.QWidget(Form)
        self.widget_10.setGeometry(QtCore.QRect(150, 680, 131, 61))
        self.widget_10.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_10.setObjectName("widget_10")
        self.widget_11 = QtWidgets.QWidget(Form)
        self.widget_11.setGeometry(QtCore.QRect(660, 480, 111, 61))
        self.widget_11.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_11.setObjectName("widget_11")
        self.widget_12 = QtWidgets.QWidget(Form)
        self.widget_12.setGeometry(QtCore.QRect(660, 540, 111, 61))
        self.widget_12.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_12.setObjectName("widget_12")
        self.widget_13 = QtWidgets.QWidget(Form)
        self.widget_13.setGeometry(QtCore.QRect(150, 510, 131, 61))
        self.widget_13.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_13.setObjectName("widget_13")
        self.widget_14 = QtWidgets.QWidget(Form)
        self.widget_14.setGeometry(QtCore.QRect(150, 450, 131, 61))
        self.widget_14.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_14.setObjectName("widget_14")
        self.widget_15 = QtWidgets.QWidget(Form)
        self.widget_15.setGeometry(QtCore.QRect(330, 330, 101, 61))
        self.widget_15.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_15.setObjectName("widget_15")
        self.lcdNumber_0 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_0.setGeometry(QtCore.QRect(1220, 190, 150, 31))
        self.lcdNumber_0.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_0.setObjectName("lcdNumber_0")
        self.lcdNumber_1 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_1.setGeometry(QtCore.QRect(1000, 190, 150, 31))
        self.lcdNumber_1.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_1.setObjectName("lcdNumber_1")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_2.setGeometry(QtCore.QRect(790, 350, 150, 31))
        self.lcdNumber_2.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_3.setGeometry(QtCore.QRect(790, 550, 150, 31))
        self.lcdNumber_3.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_4.setGeometry(QtCore.QRect(1010, 630, 150, 31))
        self.lcdNumber_4.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_5.setGeometry(QtCore.QRect(1230, 630, 150, 31))
        self.lcdNumber_5.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_6.setGeometry(QtCore.QRect(410, 100, 150, 31))
        self.lcdNumber_6.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_7.setGeometry(QtCore.QRect(210, 100, 150, 31))
        self.lcdNumber_7.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_8.setGeometry(QtCore.QRect(500, 350, 150, 31))
        self.lcdNumber_8.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_9.setGeometry(QtCore.QRect(500, 560, 150, 31))
        self.lcdNumber_9.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_10.setGeometry(QtCore.QRect(20, 100, 150, 31))
        self.lcdNumber_10.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_11.setGeometry(QtCore.QRect(310, 400, 150, 31))
        self.lcdNumber_11.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_12.setGeometry(QtCore.QRect(310, 600, 150, 31))
        self.lcdNumber_12.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.lcdNumber_13 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_13.setGeometry(QtCore.QRect(1120, 570, 150, 31))
        self.lcdNumber_13.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.lcdNumber_14 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_14.setGeometry(QtCore.QRect(1290, 500, 150, 31))
        self.lcdNumber_14.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.widget_16 = QtWidgets.QWidget(Form)
        self.widget_16.setGeometry(QtCore.QRect(810, 100, 111, 71))
        self.widget_16.setStyleSheet("border-radius: 10px;\n"
"image: url(:/unchecked-radio-button-off-96.png);")
        self.widget_16.setObjectName("widget_16")
        self.widget_17 = QtWidgets.QWidget(Form)
        self.widget_17.setGeometry(QtCore.QRect(670, 100, 111, 71))
        self.widget_17.setStyleSheet("border-radius: 10px;\n"
"image: url(:/unchecked-radio-button-off-96.png);")
        self.widget_17.setObjectName("widget_17")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(1150, 490, 91, 61))
        self.widget.setStyleSheet("image: url(:/joystick-500.png);")
        self.widget.setObjectName("widget")
        self.lcdNumber_15 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_15.setGeometry(QtCore.QRect(960, 500, 150, 31))
        self.lcdNumber_15.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.lcdNumber_16 = QtWidgets.QLCDNumber(Form)
        self.lcdNumber_16.setGeometry(QtCore.QRect(1120, 440, 150, 31))
        self.lcdNumber_16.setStyleSheet("background-color:rgb(90, 90, 138);\n"
"border: 2px solidrgb(255, 182, 12) ;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"color: rgb(255, 255, 255);")
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.widget_6 = QtWidgets.QWidget(Form)
        self.widget_6.setGeometry(QtCore.QRect(0, 450, 131, 61))
        self.widget_6.setStyleSheet("border-radius: 10px;\n"
"image: url(:/toggle-off-80.png);")
        self.widget_6.setObjectName("widget_6")
        self.widget_Dashboard_10 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_10.setGeometry(QtCore.QRect(20, 140, 150, 150))
        self.widget_Dashboard_10.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_10.setObjectName("widget_Dashboard_10")
        self.widget_Dashboard_7 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_7.setGeometry(QtCore.QRect(210, 140, 150, 150))
        self.widget_Dashboard_7.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_7.setObjectName("widget_Dashboard_7")
        self.widget_Dashboard_6 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_6.setGeometry(QtCore.QRect(410, 140, 150, 150))
        self.widget_Dashboard_6.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_6.setObjectName("widget_Dashboard_6")
        self.widget_Dashboard_11 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_11.setGeometry(QtCore.QRect(310, 440, 150, 150))
        self.widget_Dashboard_11.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_11.setObjectName("widget_Dashboard_11")
        self.widget_Dashboard_12 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_12.setGeometry(QtCore.QRect(310, 640, 150, 150))
        self.widget_Dashboard_12.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_12.setObjectName("widget_Dashboard_12")
        self.widget_Dashboard_8 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_8.setGeometry(QtCore.QRect(500, 390, 150, 150))
        self.widget_Dashboard_8.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_8.setObjectName("widget_Dashboard_8")
        self.widget_Dashboard_9 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_9.setGeometry(QtCore.QRect(500, 600, 150, 150))
        self.widget_Dashboard_9.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_9.setObjectName("widget_Dashboard_9")
        self.widget_Dashboard_1 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_1.setGeometry(QtCore.QRect(1000, 230, 150, 150))
        self.widget_Dashboard_1.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_1.setObjectName("widget_Dashboard_1")
        self.widget_Dashboard_0 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_0.setGeometry(QtCore.QRect(1220, 230, 150, 150))
        self.widget_Dashboard_0.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_0.setObjectName("widget_Dashboard_0")
        self.widget_Dashboard_2 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_2.setGeometry(QtCore.QRect(790, 390, 150, 150))
        self.widget_Dashboard_2.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_2.setObjectName("widget_Dashboard_2")
        self.widget_Dashboard_3 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_3.setGeometry(QtCore.QRect(790, 590, 150, 150))
        self.widget_Dashboard_3.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_3.setObjectName("widget_Dashboard_3")
        self.widget_Dashboard_4 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_4.setGeometry(QtCore.QRect(1010, 670, 150, 150))
        self.widget_Dashboard_4.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_4.setObjectName("widget_Dashboard_4")
        self.widget_Dashboard_5 = AnalogGaugeWidget(Form)
        self.widget_Dashboard_5.setGeometry(QtCore.QRect(1230, 670, 150, 150))
        self.widget_Dashboard_5.setStyleSheet("background-color: rgb(40, 38, 38);")
        self.widget_Dashboard_5.setObjectName("widget_Dashboard_5")
        self.comportbox = QtWidgets.QComboBox(Form)
        self.comportbox.setGeometry(QtCore.QRect(380, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.comportbox.setFont(font)
        self.comportbox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        #self.comportbox.setStyleSheet("background-color:rgb(182, 171, 193);\n""padding-left:10px;\n""selection-background-color:rgb(182, 171, 193);\n")
        self.comportbox.setStyleSheet('''
                QComboBox{
                        background-color:rgb(182, 171, 193);
                        padding-left:10px;
                        selection-background-color:rgb(182, 171, 193);
                } 
               
        '''
        )
        self.comportbox.setObjectName("comportbox")
        self.text = QtWidgets.QLabel(Form)
        self.text.setGeometry(QtCore.QRect(20, 30,355, 31))
        self.text.setStyleSheet("color: rgb(85, 85, 127);\n"
"font: 75 22pt \"Berlin Sans FB Demi\";\n"
"")
        self.text.setObjectName("text")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(500, 30, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(206, 221, 255);\n"
"")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "DYU_test"))
        self.widget_0.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_1.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_2.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_3.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_4.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_5.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_7.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_8.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_9.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_10.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_11.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_12.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_13.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_14.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_15.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_16.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_17.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.widget_6.setToolTip(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.text.setText(_translate("Form", "Select COM to search :"))
        self.pushButton.setText(_translate("Form", "start"))
import icon
